cross_c_stdlib:
  - sysroot                  # [linux]
  - m2w64-sysroot            # [win and x86_64]
cross_c_stdlib_version:
  - '2.28'                   # [linux]
  - '12'                     # [win and x86_64]
c_stdlib_version:
  - '2.28'                   # [linux]
  - '12'                     # [win and x86_64]

m2w64_c_compiler:            # [win and x86_64]
  - gcc                      # [win and x86_64]
m2w64_c_compiler_version:    # [win and x86_64]
  - '13'                     # [win and x86_64]
m2w64_c_stdlib:              # [win and x86_64]
  - m2w64-sysroot            # [win and x86_64]
m2w64_c_stdlib_version:      # [win and x86_64]
  - '12'                     # [win and x86_64]
m2w64_cxx_compiler:          # [win and x86_64]
  - gxx                      # [win and x86_64]
m2w64_cxx_compiler_version:  # [win and x86_64]
  - '13'                     # [win and x86_64]
