cross_c_stdlib:
  - sysroot                  # [linux]
  - m2w64-sysroot            # [win and x86_64]
cross_c_stdlib_version:
  - '2.28'                   # [linux]
  - '12'                     # [win and x86_64]
c_stdlib_version:
  - '2.28'                   # [linux]
  - '12'                     # [win and x86_64]

m2w64_c_compiler:            # [(linux or win) and x86_64]
  - gcc                      # [(linux or win) and x86_64]
m2w64_c_compiler_version:    # [(linux or win) and x86_64]
  - '13'                     # [(linux or win) and x86_64]
m2w64_c_stdlib:              # [(linux or win) and x86_64]
  - m2w64-sysroot            # [(linux or win) and x86_64]
m2w64_c_stdlib_version:      # [(linux or win) and x86_64]
  - '12'                     # [(linux or win) and x86_64]
m2w64_cxx_compiler:          # [(linux or win) and x86_64]
  - gxx                      # [(linux or win) and x86_64]
m2w64_cxx_compiler_version:  # [(linux or win) and x86_64]
  - '13'                     # [(linux or win) and x86_64]

docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and x86_64]
