c_stdlib_version:
  - if: osx
    then: 11.3

MACOSX_SDK_VERSION:
  - if: osx
    then: 11.3

MACOSX_DEPLOYMENT_TARGET:
  - if: osx
    then: 11.3

CONDA_BUILD_SYSROOT:
  - if: osx
    then: /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
