c_stdlib_version:
  - "2.28"  # [linux]
qemu_noarch_dependencies:
  - capstone
  - epoxy
  - gnutls
  - glib
  - glfw
  - gtk3
  - gmp
  - libcurl
  - libgcrypt
  - libgsasl
  - libjpeg-turbo
  - libpng
  - libusb
  - lzfse
  - lzo
  - nettle
  - openssh
  - pixman
  - sdl2
  - sdl2_image
  - snappy
  - sphinx >=3.4.3
  - sphinx-rtd-theme >=0.5
  - zlib

qemu_linux_dependencies:
  - alsa-lib
  - dtc
  - jack
  - keyutils
  - libaio
  - libegl-devel
  - libfdt
  - libnuma
  - libslirp
  - libudev1
  - liburing
  - libxkbcommon

# - libseccomp  : causes error: 'CLONE_NEWCGROUP' undeclared

qemu_osx_dependencies:
  - dtc
  - libfdt
  - llvmdev
  - zstd

qemu_system_execs:
  - "aarch64"

#  - "alpha"
#  - "arm"
#  - "avr"
#  - "cris"
#  - "hppa"
#  - "i386"
#  - "loongarch64"
#  - "m68k"
#  - "microblaze"
#  - "microblazeel"
#  - "mips"
#  - "mips64"
#  - "mips64el"
#  - "mipsel"
#  - "or1k"
#  - "ppc"
#  - "ppc64"
#  - "riscv32"
#  - "riscv64"
#  - "rx"
#  - "s390x"
#  - "sh4"
#  - "sh4eb"
#  - "sparc"
#  - "sparc64"
#  - "tricore"
#  - "x86_64"
#  - "xtensa"
#  - "xtensaeb"
