{% set name = "qemu-system" %}
{% set version = "9.1.0" %}

{% set qemu_system_share = [
    "edk2-aarch64-code.fd", "edk2-arm-code.fd", "edk2-arm-vars.fd", "edk2-riscv-code.fd", "edk2-riscv-vars.fd",
    "edk2-i386-code.fd", "edk2-i386-secure-code.fd", "edk2-i386-vars.fd", "edk2-x86_64-code.fd",
    "edk2-x86_64-secure-code.fd"
  ]
%}
{% set qemu_system_firmware = [
    "50-edk2-i386-secure.json", "50-edk2-x86_64-secure.json", "60-edk2-aarch64.json", "60-edk2-arm.json",
    "60-edk2-i386.json", "60-edk2-x86_64.json"
  ]
%}
{% set qemu_system_tools = [
      "elf2dmp", "qemu-io", "qemu-edid", "qemu-nbd", 
      "qemu-img", "qemu-storage-daemon"
    ]
%}
{% set qemu_system_tools_linux = [
    "qemu-ga", "qemu-vmsr-helper", "qemu-pr-helper"
  ]
%}
{% set qemu_system_icons = [
    "128x128/apps/qemu.png", "16x16/apps/qemu.png", "24x24/apps/qemu.png", "64x64/apps/qemu.png",
    "256x256/apps/qemu.png", "32x32/apps/qemu.bmp", "32x32/apps/qemu.png", "48x48/apps/qemu.png",
    "512x512/apps/qemu.png", "scalable/apps/qemu.svg"
  ]
%}

# {% set qemu_system_locale = [
#     "bg", "de_DE", "fr_FR", "hu", "it", "sv", "tr", "uk", "zh_CN"
#   ]
# %}

package:
  name: qemu-system-split
  version: {{ version }}

source:
  - url: https://gitlab.com/qemu-project/qemu/-/archive/v{{ version }}/qemu-v{{ version }}.tar.gz
    sha256: 7a0d0e6b7e955d03c0d418025d8551146dbd4ec0128c1fb7dec791b94de7bbb7
    folder: qemu_source
    patches:
      - patches/0002-osx-attr-meson.build.patch  # [osx]
      - patches/0003-osx-block_file-posix.c.patch  # [osx]
      - patches/0004-osx-audio_coreaudio.m.patch  # [osx]
      - patches/0002-win-configure-pyvenv.patch  # [win]
      - patches/0003-win-dbg-MESONINTROSPECT.patch  # [win]
      - patches/0004-win-fix-PYTHON-var-Makefile.patch  # [win]
      - patches/0005-win-fix-tracetool-path.patch  # [win]

  - url: https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-virt-{{ alpine_iso_version }}-aarch64.iso  # [osx]
    sha256: dbd0c2eaa0bfa39e18d075dae07760a9055ffdee0a338c8a35059413b0f76fec  # [osx]
  - url: https://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd  # [osx]
    sha256: 42f915c44de6858f69ae6f1ffc9eaa3884d1b2ca97a7537d81312fb0dfd712cd  # [osx]
  # - url: https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-minirootfs-3.20.3-aarch64.tar.gz  # [osx]
  #   sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  # [osx]

build:
  number: 0
  skip: True  # [win]
  script_env:
    - CONDA_QEMU_INSTALL_DIR=${PREFIX}

requirements:
  build:
    - git
    - ninja
    - pkg-config
    
    {% if target_platform == "linux-64" or target_platform == "osx-64" %}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - meson
    {% endif %}
    # - patchelf
    # - python-qemu-qmp

    {% if target_platform == "osx-64" %}
    - clang_osx-arm64
    {% endif %}
    
    {% if target_platform == "win-64" %}
    - {{ compiler("m2w64_c") }}
    - {{ stdlib("m2w64_c") }}
    - binutils
    - gettext
    - m2-autoconf
    - m2-automake-wrapper
    - m2-findutils
    - m2-grep
    - m2-libtool
    - m2-make
    - m2-which
    - packaging
    {% endif %}
  host:
    - capstone
    - epoxy
    - gnutls
    - glib
    - glfw
    - gtk3
    - gmp
    - libcurl
    - libgcrypt
    - libgsasl
    - libjpeg-turbo
    - libpng
    - libusb
    - lzfse
    - lzo
    - nettle
    - openssh
    - pixman
    - sdl2
    - sdl2_image
    - snappy
    - sphinx >=3.4.3
    - sphinx-rtd-theme >=0.5
    - zlib

    {% if target_platform == "linux-64" %}
    - alsa-lib
    - dtc
    - jack
    - keyutils
    - libaio
    - libegl-devel
    - libfdt
    - libnuma
    - libslirp
    - libudev1
    - liburing
    - libxkbcommon
    {% endif %}

    {% if target_platform == "osx-64" %}
      {% for dep in qemu_osx_dependencies %}
    - {{ dep }}
      {% endfor %}
    {% endif %}

    {% if target_platform == "win-64" %}
    - bzip2
    {% endif %}

outputs:
  - name: qemu-system-shared-resources
    files:
      {% for file in qemu_system_tools %}
      - bin/{{ file }}
      {% endfor %}

      {% if target_platform == "linux-64" %}
        {% for file in qemu_system_tools_linux %}
      - bin/{{ file }}
        {% endfor %}
      {% endif %}

      {% for file in qemu_system_share %}
      - share/qemu/{{ file }}
      {% endfor %}

      {% for file in qemu_system_firmware %}
      - share/qemu/firmware/{{ file }}
      {% endfor %}

      {% for file in qemu_system_icons %}
      - share/icons/hicolor/{{ file }}
      {% endfor %}

      - share/applications/qemu.desktop
      - libexec/qemu-bridge-helper
    requirements:
      build:
          - {{ compiler("c") }}
          - {{ stdlib("c") }}
      host:
        - capstone
        - epoxy
        - gnutls
        - glib
        - glfw
        - gtk3
        - gmp
        - libcurl
        - libgcrypt
        - libgsasl
        - libjpeg-turbo
        - libpng
        - libusb
        - lzfse
        - lzo
        - nettle
        - openssh
        - pixman
        - sdl2
        - sdl2_image
        - snappy
        - sphinx >=3.4.3
        - sphinx-rtd-theme >=0.5
        - zlib

        {% if target_platform == "linux-64" %}
        - alsa-lib
        - dtc
        - jack
        - keyutils
        - libaio
        - libegl-devel
        - libfdt
        - libnuma
        - libslirp
        - libudev1
        - liburing
        - libxkbcommon
        {% endif %}

        {% if target_platform == "osx-64" %}
        - dtc
        - libfdt
        - llvmdev
        - zstd
        {% endif %}

        {% if target_platform == "win-64" %}
        - bzip2
        {% endif %}
      run:
        - capstone
        - epoxy
        - gnutls
        - glib
        - glfw
        - gtk3
        - gmp
        - libcurl
        - libgcrypt
        - libgsasl
        - libjpeg-turbo
        - libpng
        - libusb
        - lzfse
        - lzo
        - nettle
        - openssh
        - pixman
        - sdl2
        - sdl2_image
        - snappy
        - sphinx >=3.4.3
        - sphinx-rtd-theme >=0.5
        - zlib

        {% if target_platform == "linux-64" %}
        - alsa-lib
        - dtc
        - jack
        - keyutils
        - libaio
        - libegl-devel
        - libfdt
        - libnuma
        - libslirp
        - libudev1
        - liburing
        - libxkbcommon
        {% endif %}

        {% if target_platform == "osx-64" %}
        - dtc
        - libfdt
        - llvmdev
        - zstd
        {% endif %}


  - name: qemu-system-{{ qemu_system_execs }}
    files:
      - bin/qemu-system-{{ qemu_system_execs }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      host:
        - {{ pin_subpackage("qemu-system-shared-resources") }}

        - capstone
        - epoxy
        - gnutls
        - glib
        - glfw
        - gtk3
        - gmp
        - libcurl
        - libgcrypt
        - libgsasl
        - libjpeg-turbo
        - libpng
        - libusb
        - lzfse
        - lzo
        - nettle
        - openssh
        - pixman
        - sdl2
        - sdl2_image
        - snappy
        - sphinx >=3.4.3
        - sphinx-rtd-theme >=0.5
        - zlib

        {% if target_platform == "linux-64" %}
        - alsa-lib
        - dtc
        - jack
        - keyutils
        - libaio
        - libegl-devel
        - libfdt
        - libnuma
        - libslirp
        - libudev1
        - liburing
        - libxkbcommon
        {% endif %}

        {% if target_platform == "osx-64" %}
        - dtc
        - libfdt
        - llvmdev
        - zstd
        {% endif %}

        {% if target_platform == "win-64" %}
        - bzip2
        {% endif %}
      run:
        - {{ pin_subpackage("qemu-system-shared-resources") }}

        - capstone
        - epoxy
        - gnutls
        - glib
        - glfw
        - gtk3
        - gmp
        - libcurl
        - libgcrypt
        - libgsasl
        - libjpeg-turbo
        - libpng
        - libusb
        - lzfse
        - lzo
        - nettle
        - openssh
        - pixman
        - sdl2
        - sdl2_image
        - snappy
        - sphinx >=3.4.3
        - sphinx-rtd-theme >=0.5
        - zlib

        {% if target_platform == "linux-64" %}
        - alsa-lib
        - dtc
        - jack
        - keyutils
        - libaio
        - libegl-devel
        - libfdt
        - libnuma
        - libslirp
        - libudev1
        - liburing
        - libxkbcommon
        {% endif %}

        {% if target_platform == "osx-64" %}
        - dtc
        - libfdt
        - llvmdev
        - zstd
        {% endif %}

        {% if target_platform == "win-64" %}
        - bzip2
        {% endif %}
    test:
      - test -f $PREFIX/bin/qemu-system-{{ qemu_system_execs }}  # [not win]
      - qemu-system-{{ qemu_system_execs }} --version  # [not win]


about:
  home: https://gitlab.com/qemu-project/qemu
  summary: 'QEMU is a generic and open source machine & userspace emulator and virtualizer.'
  description: |
    QEMU is capable of emulating a complete machine in software without any
    need for hardware virtualization support. By using dynamic translation,
    it achieves very good performance. QEMU can also integrate with the Xen
    and KVM hypervisors to provide emulated hardware while allowing the
    hypervisor to manage the CPU. With hypervisor support, QEMU can achieve
    near native performance for CPUs. When QEMU emulates CPUs directly it is
    capable of running operating systems made for one machine (e.g. an ARMv7
    board) on a different machine (e.g. an x86_64 PC board).
    
    QEMU is also capable of providing userspace API virtualization for Linux
    and BSD kernel interfaces. This allows binaries compiled against one
    architecture ABI (e.g. the Linux PPC64 ABI) to be run on a host using a
    different architecture ABI (e.g. the Linux x86_64 ABI). This does not
    involve any hardware emulation, simply CPU and syscall emulation.
    
    QEMU aims to fit into a variety of use cases. It can be invoked directly
    by users wishing to have full control over its behaviour and settings.
    It also aims to facilitate integration into higher level management
    layers, by providing a stable command line interface and monitor API.
    It is commonly invoked indirectly via the libvirt library when using
    open source applicationss such as oVirt, OpenStack and virt-manager.
    QEMU as a whole is released under the GNU General Public License,
    version 2. For full licensing details, consult the LICENSE file.  license: GPL-2.0-only
  license_file:
    - qemu_source/COPYING
    - qemu_source/COPYING.LIB
    - qemu_source/LICENSE

extra:
  recipe-maintainers:
    -  MementoRC
  feedstock-name: qemu-system
