context:
  name: qemu-system
  version: "9.1.0"
  build_num: 0

recipe:
  name: qemu-system-split
  version: ${{ version }}

source:
  - url: https://gitlab.com/qemu-project/qemu/-/archive/v${{ version }}/qemu-v${{ version }}.tar.gz
    sha256: 7a0d0e6b7e955d03c0d418025d8551146dbd4ec0128c1fb7dec791b94de7bbb7
    target_directory: qemu_source
    patches:
      - if: linux
        then:
          - patches/0002-linux-set-MAP_FIXED_NOREPLACE.patch
      - if: osx
        then:
          - patches/0002-osx-attr-meson.build.patch
          - patches/0003-osx-block_file-posix.c.patch
          - patches/0004-osx-audio_coreaudio.m.patch
      - if: win
        then:
          - patches/0002-win-configure-pyvenv.patch
          - patches/0003-win-dbg-MESONINTROSPECT.patch
          - patches/0004-win-fix-PYTHON-var-Makefile.patch
          - patches/0005-win-fix-tracetool-path.patch

  # - url: https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-minirootfs-3.20.3-aarch64.tar.gz  # [osx]
  #   sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  # [osx]
  - if: osx
    then:
      - url: https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/aarch64/alpine-virt-${{ alpine_iso_version }}-aarch64.iso
        sha256: dbd0c2eaa0bfa39e18d075dae07760a9055ffdee0a338c8a35059413b0f76fec
      - url: https://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd
        sha256: 42f915c44de6858f69ae6f1ffc9eaa3884d1b2ca97a7537d81312fb0dfd712cd

