{% set name = "dydxprotocol-v4-client-js" %}
{% set version = "1.1.26" %}

package:
  name: dydxprotocol-v4-client-js-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-clients/archive/refs/tags/v4-client-js@{{ version }}.tar.gz
  sha256: fe0e03a72c1fdf5a6ebb06a14f8c0ab45c93de821d29be487b0a9d6a6c96ea79
  folder: js_module_source
  patches:
    - patches/0001-js-missing-binding.gyp.patch
    - patches/0002-js-package.json.patch

build:
  number: 0

requirements:
  build:
    - dydxprotocol-node-service-base-dev
    - typescript-eslint-eslint-plugin
    - typescript-eslint-parser
    - eslint-config-prettier
    - prettier
    - nodejs >=18
    - pnpm
    - pnpm-licenses
  host:
    - bash  # [unix]
    - dydxprotocol-v4-proto-js
    - nodejs >=18

outputs:
  - name: dydxprotocol-v4-client-js
    script: helpers/install-js.sh
    build:
      noarch: nodejs
    requirements:
      host:
        - nodejs >=18
      run:
        - dydxprotocol-v4-proto-js
        - nodejs >=18
    test:
      commands:
        - test -d $PREFIX/lib/node_modules/@dydxprotocol/v4-client-js  # [unix]
        - if not exist %PREFIX%\\lib\\node_modules\\@dydxprotocol\\v4-client-js exit 1  # [win]

about:
  home: https://github.com/dydxprotocol/v4-clients
  summary: 'The dYdX Chain Clients used for placing transactions and querying the dYdX chain.'
  description: |
    The dYdX Chain Clients used for placing transactions and querying the dYdX chain.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: dydxprotocol-v4-client-js
