{% set name = "dydxprotocol-v4-client-js" %}
{% set version = "1.1.31" %}

package:
  name: dydxprotocol-v4-client-js-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-clients/archive/refs/tags/v4-client-js@{{ version }}.tar.gz
  sha256: eb6ffc4e53aa0a22f195092f2102fb5233c5c4dda7b11700208a1974d1428297
  folder: js_module_source
  patches:
    - patches/0001-types-long-options.patch

build:
  number: 0

requirements:
  build:
    - nodejs >=18
    - pnpm
    - pnpm-licenses
  host:
    - bash  # [unix]
    - nodejs >=18

outputs:
  - name: dydxprotocol-v4-client-js
    script: helpers/install-js.sh  # [unix]
    script: helpers/install-js.bat  # [win]
    requirements:
      host:
        - nodejs >=18
      run:
        - nodejs >=18
    test:
      commands:
        - test -d $PREFIX/lib/node_modules/@dydxprotocol/v4-client-js  # [unix]
        - if not exist %PREFIX%\\lib\\node_modules\\@dydxprotocol\\v4-client-js exit 1  # [win]

  # - Naming conversion
  - name: dydxprotocol_v4_client_js
    requirements:
      run:
        - {{ pin_subpackage('dydxprotocol-v4-client-js', exact=True) }}
    test:
      commands:
        - test -d $PREFIX/lib/node_modules/@dydxprotocol/v4-client-js  # [unix]
        - if not exist %PREFIX%\\lib\\node_modules\\@dydxprotocol\\v4-client-js exit /b 1  # [win]

about:
  home: https://github.com/dydxprotocol/v4-clients
  summary: 'The dYdX Chain Clients used for placing transactions and querying the dYdX chain.'
  description: |
    The dYdX Chain Clients used for placing transactions and querying the dYdX chain.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: dydxprotocol-v4-client-js
