{% set name = "dydxprotocol-node-service-base-dev" %}
{% set version = "0.3.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/node-service-base-dev/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 19d5a8bd24b4c3f14ea9f3bc51060a2523149ad8fe5a46f102c3019fcb941698
  patches:
    - patches/0001-resolve-audit-fail.patch
    - patches/0002-correct-testUtils.ts.patch
    - patches/0003-win-build-package.json.patch  # [win]

build:
  # skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/@dydxprotocol/node-service-base-dev  # [unix]
    # - if not exist %PREFIX%\\lib\\node_modules\\@dydxprotocol\\node-service-base-dev exit 1  # [win]

about:
  home: https://github.com/dydxprotocol/node-service-base-dev
  summary: 'Shared dev dependencies, development configuration, and utilities for Node libraries and services.'
  description: |
    Includes the following:
      eslint configs
      jest configs
      tsconfig.json and tsconfig.eslint.json
      test utils: advancePromiseQueue, asMock, mockNow
  license: Apache-2.0
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt

extra:
  recipe-maintainers:
    - MementoRC
