{% set name = "v4-client-js" %}
{% set version = "1.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-clients/archive/refs/tags/v4-client-js@{{ version }}.tar.gz
  sha256: b0b1651b5ffdfe1ee70bcd03e8b38ca2c74dd12de65f119ca69c64c50265ee40

build:
  number: 0
  missing_dso_whitelist:
    - "*/libc.musl-x86_64.so.1"  # [linux]
    # Added as run deps: libgcc-ng (via compiler strong run_exports)
    # - "*/libgcc_s.so.1"  # [linux]
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - nodejs
  host:
    - nodejs
  run:
    - libgcc-ng  # [linux]
    - gcc_impl_{{ target_platform }}  # [linux]

test:
  commands:
    - test -f $PREFIX/share/@dydxprotocol/v4-client-js/version  # [unix]

about:
  home: https://github.com/dydxprotocol/v4-clients
  summary: 'The dYdX Chain Client Typescript client is used for placing transactions and querying the dYdX chain.'
  description: |
    The dYdX Chain Client Typescript client is used for placing transactions and querying the dYdX chain.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
