{% set name = "dydx-v4-proto-cpp" %}
{% set version = "1.1.31" %}

{% set so_version = "0.0.1" %}
{% set so_major_version = so_version.split('.')[0] %}

package:
  name: libdydx_v4_proto-{{ so_major_version }}
  version: {{ version }}

source:
  folder: all-sources
  url: https://github.com/dydxprotocol/v4-clients/archive/refs/tags/v4-client-js@{{ version }}.tar.gz
  sha256: eb6ffc4e53aa0a22f195092f2102fb5233c5c4dda7b11700208a1974d1428297
  patches:
    - patches/0001-build-proto-only.patch
    - patches/0002-remove-unused-packages.patch
    - patches/0003-add-sharedlib-install.patch
    - patches/0004-remove-FetchContent.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libdydx_v4_proto-' ~ so_major_version) }}
  ignore_run_exports:
    - ucrt  # [win]
    - vc14_runtime  # [win

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.25
    - ninja
    - pkg-config
  host:
    - catch2
    - libabseil >=20240116
    - libprotobuf >=4.22
test:
  commands:
    - test -f ${PREFIX}/lib/libdydx_v4_proto${SHLIB_EXT}.{{ so_major_version }}  # [linux]
    - test -f ${PREFIX}/lib/libdydx_v4_proto.{{ so_major_version }}${SHLIB_EXT}  # [osx]
    - if not exist %PREFIX%\\Library\\bin\\dydx_v4_proto-{{ so_major_version }}%SHLIB_EXT% exit 1  # [win]
    - test -f ${PREFIX}/lib/libdydx_v4_proto${SHLIB_EXT}.{{ so_version }}  # [linux]
    - test -f ${PREFIX}/lib/libdydx_v4_proto.{{ so_version }}${SHLIB_EXT}  # [osx]

about:
  home: https://github.com/dydxprotocol/v4-clients
  summary: 'The dYdX Chain Clients used for placing transactions and querying the dYdX chain.'
  description: |
    The dYdX Chain Clients used for placing transactions and querying the dYdX chain.
  license: AGPL-3.0-only
  license_file:
    - all-sources/LICENSE

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: dydx-v4-proto-cpp
