{% set name = "dydx-v4-proto" %}
{% set version = "5.0.6" %}

package:
  name: dydx-v4-proto-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-chain/archive/refs/tags/protocol/v{{ version }}.tar.gz
  sha256: c787e4221bf65546996876b795efd2268eae40b1cfc3adcf74277c63883dc712

build:
  number: 0

requirements:
  build:
    - nodejs >=18
  host:
    - buf
    - grpcio-tools >=1.54
    - grpcio >=1.54
    - make
    - nodejs >=18
    - perl
    - pnpm
    - python >=3.9

outputs:
  - name: dydx_v4_proto_py
    script: install-py.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.9
      run:
        - grpcio-tools >=1.54
        - grpcio >=1.54
        - protobuf >=4.23
        - python >=3.9
    test:
      imports:
        - v4_proto
      requires:
        - pip
      commands:
        - pip check
      downstreams:
        - dydx-v4-clients
        - dydx-v4-clients-py
        - dydx_v4_clients_py

  # - name: dydx_v4_proto_js
  #   script: install-js.sh
  #   requirements:
  #     host:
  #       - nodejs >=18
  #       - pnpm
  #       - pnpm-licenses
  #     run:
  #       - nodejs >=18
  #   test:
  #     commands:
  #       - test -f $PREFIX/share/@dydxprotocol/v4-proto-js/version  # [unix]

  # - Naming conversion
  - name: dydx-v4-proto-py
    requirements:
      run:
        - dydx_v4_proto_py {{ version }}

  # Package name required by v4-client upstream pyproject.toml
  - name: v4-proto
    requirements:
      run:
        - dydx_v4_proto_py {{ version }}

  # - name: dydx-v4-proto-js
  #   requirements:
  #     run:
  #       - dydx_v4_proto_js {{ version }}

about:
  home: https://github.com/dydxprotocol/v4-chain
  summary: 'The dYdX Chain Client Typescript client is used for placing transactions and querying the dYdX chain.'
  description: |
    The dYdX Chain Client Typescript client is used for placing transactions and querying the dYdX chain.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: dydx-v4-proto
