context:
  name: apple-bindgen
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/youknowone/apple-sys/archive/refs/tags/${{ version }}.tar.gz
  sha256: 9654f2bda892c365888c0d826267cf3e867834d4d45a3f61b0175aaded7ec671
  patches:
    - if: osx
      then:
        - patches/update-bindgen.patch
  #       - patches/bindgen-clang-path.patch
  #       - patches/debug-test-sdk.patch

build:
  number: 0
  skip:
    - linux
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - libclang ${{ c_compiler_version }}.*
  host:
    - setuptools-rust

tests:
  - package_contents:
      files:
        - bin/apple-bindgen
  - script:
      - apple-bindgen --help

about:
  homepage: https://github.com/youknowone/apple-sys
  summary: 'The auto-managed -sys crate for Apple platforms.'
  description: |
    The auto-managed -sys crate for Apple platforms using
    bindgen directly from build environment.
  license: BSD-2-Clause
  license_file:
    - LICENSE
  repository: https://github.com/youknowone/apple-sys

extra:
  recipe-maintainers:
    - MementoRC
