{% set name = "dydx-v4-clients" %}
{% set version = "1.1.26" %}

package:
  name: dydx-v4-clients-split
  version: {{ version }}

source:
  url: https://github.com/dydxprotocol/v4-clients/archive/refs/tags/v4-client-js@{{ version }}.tar.gz
  sha256: fe0e03a72c1fdf5a6ebb06a14f8c0ab45c93de821d29be487b0a9d6a6c96ea79
  patches:
    - patches/0001-js-missing-binding.gyp.patch
    - patches/0002-js-package.json.patch
    - patches/0001-cpp-add-abseil.patch
    - patches/0002-cpp-remove-beast-specification.patch
    - patches/0003-cpp-support-protobuf_MODULE_COMPATIBLE.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.25
    - ninja
    - pnpm
    - pnpm-licenses
  host:
    - catch2
    - dydx-v4-proto-py >=5.0.6
    - fmt
    - libabseil >=20240116
    - libbip3x
    - libboost-devel
    - libprotobuf
    - libtoolbox
    - make
    - nlohmann_json
    - nodejs >=18
    - openssl
    - pkg-config
    - poetry
    - python >=3.9
    - simplejson
    - typing-extensions >=4.12.2
    - zlib
    - websocket-client >=1.7.0

outputs:
  - name: dydx_v4_client_py
    script: install-py.sh
    requirements:
      host:
        - pip
        - python >=3.9
      run:
        - bip-utils >=2.9.3
        - dydx-v4-proto-py
        - ecdsa >=0.19
        - httpx >=0.27
        - python >=3.9
        - websocket-client >=1.7.0
    test:
      imports:
        - dydx_v4_client
      requires:
        - pip
      commands:
        - pip check

  # - name: dydx_v4_client_cpp
  #   script: install-cpp.sh
  #   requirements:
  #     build:
  #       - {{ compiler('c') }}
  #       - {{ compiler('cxx') }}
  #       - {{ stdlib("c") }}
  #       - make
  #     host:
  #       - pip
  #       - python >=3.9
  #     run:
  #       - bip-utils >=2.9.3
  #       - dydx-v4-proto-py >=4.0.1
  #       - ecdsa >=0.19
  #       - httpx >=0.27
  #       - websocket-client >=1.7.0
  #   test:
  #     imports:
  #       - dydx_v4_client
  #     requires:
  #       - pip
  #     commands:
  #       - pip check

  # - Naming conversion
  - name: dydx-v4-client-py
    requirements:
      run:
        - dydx_v4_client_py {{ version }}

about:
  home: https://github.com/dydxprotocol/v4-clients
  summary: 'The dYdX Chain Clients used for placing transactions and querying the dYdX chain.'
  description: |
    The dYdX Chain Clients used for placing transactions and querying the dYdX chain.
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt

extra:
  recipe-maintainers:
    - MementoRC
