context:
  name: openocd
  version: "0.12.0"
  build_num: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/openocd-org/openocd/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0e2bcff1ef96f0591937220dcacfe7001069ddd823514dc4ba0ea2d33504e5b5

build:
  number: ${{ build_num }}
  skip:
    - win
    - osx

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - libtool
    - ninja
    - pkg-config
  host:
    - libusb
    - meson >=1.1.0

tests:
  - package_contents:
      files:
        - include/libjaylink/libjaylink.h
        - include/libjaylink/version.h
        - lib64/pkgconfig/libjaylink.pc
        - if: linux
          then:
            - lib64/libjaylink.so
            - lib64/libjaylink.so.${{ so_version }}
            - lib64/libjaylink.so.${{ major_so_version }}


about:
  homepage: https://gitlab.zapb.de/libjaylink/libjaylink
  summary: 'libjaylink is a shared library written in C to access SEGGER J-Link.'
  description: |
    libjaylink is a shared library written in C to access SEGGER J-Link and
    compatible devices.
  license: GPL-2.0-or-later
  license_file: COPYING
  repository: https://gitlab.zapb.de/libjaylink/libjaylink

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: libjaylink
