context:
  name: openocd
  version: "0.12.0"
  jimtcl_version: "0.83"
  build_num: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/openocd-org/openocd/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 0e2bcff1ef96f0591937220dcacfe7001069ddd823514dc4ba0ea2d33504e5b5
    patches:
      # Patches from Debian 0.12.0-3 dpkg source package
      - patches/fix-unused-vars.patch
      - patches/jimtcl-0.83-include-fix.patch
      #- patches/jimtcl-expr-0.81-onwards.patch
  - url: https://github.com/msteveb/jimtcl/archive/refs/tags/${{ jimtcl_version }}.tar.gz
    sha256: 6f2df00009f5ac4ad654c1ae1d2f8ed18191de38d1f5a88a54ea99cc16936686
    target_directory: jimtcl

build:
  number: ${{ build_num }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - git
    - libtool
    - pkg-config
    - texinfo
    - if: unix
      then:
        - make
      else:
        - m2w64-make
  host:
    - capstone
    - libhidapi
    - libftdi
    - libjaylink
    - libusb
    - openssl
    - zlib


tests:
  - script: |
      openocd --version
      openocd --help


about:
  homepage: https://github.com/openocd-org/openocd
  summary: 'OpenOCD: on-chip programming and debugging support with JTAG and TAP.'
  description: |
    OpenOCD provides on-chip programming and debugging support with a
    layered architecture of JTAG interface and TAP support including:
    - (X)SVF playback to facilitate automated boundary scan and FPGA/CPLD
      programming;
    - debug target support (e.g. ARM, MIPS): single-stepping,
      breakpoints/watchpoints, gprof profiling, etc;
    - flash chip drivers (e.g. CFI, NAND, internal flash);
    - embedded TCL interpreter for easy scripting.  license: GPL-2.0-or-later
  license: GPL-2.0-or-later
  license_file: COPYING
  documentation: https://openocd.org/
  repository: https://github.com/openocd-org/openocd

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: openocd
